name: Dafoe
services:
  db:
    image: mariadb:11.5.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Dafoe
      MYSQL_USER: Atlas
      MYSQL_PASSWORD: curitiba
    ports:
      - "3307:3307"
